---
- name: Ein Test Playbook - Hello World
  hosts: all
  tasks:
    - name: Erstelle eine Datei im Home und Schreibe einen Text 
      copy:
        content: Hello World - i was here
        dest: /home/smieth/blubb.txt
